-- Creación de la tabla cuenta y movimiento
CREATE TABLE IF NOT EXISTS cuenta (
    numero_cuenta VARCHAR(255) PRIMARY KEY,
    tipo_cuenta VARCHAR(255),
    saldo_inicial NUMERIC(19, 2),
    estado BOOLEAN,
    cliente_identificacion VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS movimiento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP,
    tipo_movimiento VARCHAR(255),
    valor NUMERIC(19, 2),
    saldo NUMERIC(19, 2),
    numero_cuenta VARCHAR(255) REFERENCES cuenta (numero_cuenta),
    CONSTRAINT fk_movimiento_cuenta
        FOREIGN KEY (numero_cuenta)
        REFERENCES cuenta (numero_cuenta) ON DELETE CASCADE
);

---
ALTER TABLE movimiento
DROP CONSTRAINT movimiento_numero_cuenta_fkey;

ALTER TABLE movimiento
ADD CONSTRAINT movimiento_numero_cuenta_fkey
FOREIGN KEY (numero_cuenta)
REFERENCES cuenta (numero_cuenta) ON DELETE CASCADE;

-- Inserts para la tabla 'cuenta'
-- Se asume que los clientes Jose Lema y Marianela Montalvo ya existen con los IDs 1 y 2
-- en la tabla `cliente`.
INSERT INTO cuenta (numero_cuenta, tipo_cuenta, saldo_inicial, estado, cliente_identificacion) VALUES
('585545', 'Corriente', 1000, TRUE, '1054878'),
('478758', 'Ahorro', 2000, TRUE, '1054879'),
('495878', 'Ahorros', 0, TRUE, '1054880'),
('225487', 'Corriente', 100, TRUE, '1054878'),
('496825', 'Ahorros', 540, TRUE, '1054879');

---

-- Inserts para la tabla 'movimiento'
-- Los 'id' de las cuentas se obtienen directamente de los números de cuenta insertados previamente.
INSERT INTO movimiento (fecha, tipo_movimiento, valor, numero_cuenta) VALUES
('2022-02-10', 'Deposito', 600, '225487'),
('2022-02-08', 'Retiro', 540, '496825'),
('2022-02-08', 'Retiro', 575, '478758'),
('2022-02-10', 'Deposito', 150, '495878');